"""
templates/pdf_template.py
"""


from fpdf import FPDF


class ProductSheetPDF(FPDF):

    def header(self):

        self.set_font("Arial", "B", 16)
        self.cell(0, 10, "Product Sheet", border=False, ln=True, align="C")
        self.image("templates/logo.png", x=10, y=8, w=20)
        self.ln(10)

    def footer(self):

        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, "Generated by Nested{Loop}", 0, 0, "C")

    def add_product(self, product):

        self.set_font("Arial", "", 12)
        self.ln(5)
        self.cell(0, 10, f"{product['Name']} - {product['SKU']}", ln=True)
        self.multi_cell(0, 8, product["Description"])
        self.cell(0, 10, f"Price: £{product['Price']:.2f}", ln=True)

        if "PriceWithVAT" in product:
            self.cell(0,10, f"Price (with VAT): £{product['PriceWithVAT']:.2f}", ln=True)
        
        self.cell(0, 10, f"In stock: {product['Stock']}", ln=True)