"""
src/pdf_generator.py
"""


from fpdf import FPDF


class ProductSheetPDF(FPDF):

    def __init__(self):
        super(). __init__()
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        self.set_font("Arial", "B", 16)
        self.cell(0, 10, "Product Sheet", ln=True, align="C")
        self.image("templates/logo.png", x=10, y=8, w=20)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, "Generated by Nested{Loop}", 0, 0, "C")

    def add_product_block(self, product: dict):

        self.set_font("Arial", "", 12)
        self.set_fill_color(245, 245, 245)
        self.cell(0, 10, "", ln=True)

        y_start = self.get_y()
        self.set_x(15)

        # Name and SKU
        self.multi_cell(0, 8, f"{product['Name']} ({product['SKU']})", border=0, align='L', fill=True)
        self.set_x(15)
        self.multi_cell(0, 8, product["Description"], border=0, align='L')

        # Price
        self.set_x(15)
        self.cell(0, 8, f"Price: £{product['Price']:.2f}", ln=True)
        if "PriceWithVAT" in product:
            self.set_x(15)
            self.cell(0, 8, f"Price (with VAT): £{product['PriceWithVAT']:.2f}", ln=True)

        self.set_x(15)
        self.cell(0, 8, f"In Stock: {product['Stock']}", ln=True) 

        # Border box
        y_end = self.get_y()
        self.rect(x=10, y=y_start - 2, w=190, h=(y_end - y_start + 10))

                  